[package]
name = "strata-postgres"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
schema.workspace = true
serde = { version = "1", features = ["derive"] }
serde_json = "1"
strata-sdk.workspace = true
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync"] }
tokio-postgres = { version = "0.7.18", features = ["with-serde_json-1"] }
tracing = "0.1"

[[bin]]
name = "strata-postgres"
path = "cmd/main.rs"

[dev-dependencies]
dockertest.workspace = true
