use std::collections::HashMap;
use std::fmt::Display;
use std::str::FromStr;

use anyhow::{Context, Result, anyhow};
use strata_schema::Schema;
use serde::Deserialize;
use serde::de::DeserializeOwned;
use serde::de::value::{Error, MapDeserializer};

#[derive(Debug, Default, Clone, Deserialize)]
pub struct ProviderConfig {
    #[serde(default)]
    pub backend: String,
    #[serde(default)]
    pub mount: String,
    #[serde(flatten)]
    params: HashMap<String, String>,
}

impl ProviderConfig {
    pub fn decode<T: DeserializeOwned>(&self) -> Result<T> {
        let de = MapDeserializer::<_, Error>::new(self.params.clone().into_iter());
        T::deserialize(de).context("decoding provider config")
    }

    /// A single named setting, or `None` if the instance didn't declare it.
    pub fn param(&self, key: &str) -> Option<&str> {
        self.params.get(key).map(String::as_str)
    }

    /// The whole config flattened back to strings — how it crosses to an
    /// out-of-process provider, which rebuilds it with the same field names.
    pub fn to_map(&self) -> HashMap<String, String> {
        let mut map = self.params.clone();
        map.insert("backend".to_string(), self.backend.clone());
        map.insert("mount".to_string(), self.mount.clone());
        map
    }
}

/// A provider's settings, described and resolved. Generated by `#[config]`.
pub trait ConfigSchema: Sized {
    fn config_schema() -> Schema;
    fn from_config(config: &ProviderConfig) -> Result<Self>;
}

pub fn resolve<T>(
    config: &ProviderConfig,
    field: &str,
    env: Option<&str>,
    default: Option<&str>,
    required: bool,
) -> Result<Option<T>>
where
    T: FromStr,
    T::Err: Display,
{
    let raw = config
        .param(field)
        .map(str::to_owned)
        .or_else(|| env.and_then(|key| std::env::var(key).ok()))
        .or_else(|| default.map(str::to_owned));

    let Some(value) = raw else {
        if !required {
            return Ok(None);
        }
        let table = match config.mount.is_empty() {
            true => "the provider's config".to_string(),
            false => format!("[provider.{}]", config.mount),
        };
        return Err(match env {
            Some(key) => anyhow!("`{field}` is required: set it under {table}, or export {key}"),
            None => anyhow!("`{field}` is required: set it under {table}"),
        });
    };

    value
        .parse()
        .map(Some)
        .map_err(|e| anyhow!("`{field}`: cannot read `{value}` ({e})"))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config;

    // Each env-sensitive test owns its own variable: tests run in parallel, and a
    // shared name means one test's `remove_var` races another's `set_var`.

    #[config]
    #[derive(Debug)]
    struct Settings {
        #[config(env = "STRATA_TEST_UNSET", description = "the key", secret)]
        key: String,
        #[config(env = "STRATA_TEST_PORT", default = "8123")]
        port: u16,
        #[config(env = "STRATA_TEST_REGION")]
        region: Option<String>,
    }

    fn config(params: serde_json::Value) -> ProviderConfig {
        serde_json::from_value(params).expect("a config")
    }

    /// The config key wins; the environment is not consulted.
    #[test]
    fn param_beats_env() {
        #[config]
        struct Both {
            #[config(env = "STRATA_TEST_BOTH")]
            key: String,
        }

        unsafe { std::env::set_var("STRATA_TEST_BOTH", "from-env") };
        let both = Both::from_config(&config(serde_json::json!({ "key": "from-config" })))
            .expect("resolves");
        assert_eq!(both.key, "from-config");
    }

    /// `env` names a source, not a default: with no config key, the variable
    /// supplies the value.
    #[test]
    fn env_fills_a_missing_key() {
        #[config]
        struct FromEnv {
            #[config(env = "STRATA_TEST_ENV_ONLY")]
            key: String,
        }

        unsafe { std::env::set_var("STRATA_TEST_ENV_ONLY", "from-env") };
        let settings = FromEnv::from_config(&config(serde_json::json!({}))).expect("resolves");
        assert_eq!(settings.key, "from-env");
    }

    /// The bug this replaced: an unset variable used to yield `""`. It is now an
    /// error naming both places the value could come from.
    #[test]
    fn missing_everywhere_is_an_error() {
        let error = Settings::from_config(&config(serde_json::json!({ "mount": "books" })))
            .expect_err("no key anywhere");
        let message = error.to_string();
        assert!(message.contains("`key` is required"), "{message}");
        assert!(message.contains("[provider.books]"), "{message}");
        assert!(message.contains("STRATA_TEST_UNSET"), "{message}");
    }

    /// A declared default satisfies a field, and a supplied value still parses
    /// into the field's own type.
    #[test]
    fn default_applies_and_values_parse() {
        unsafe { std::env::remove_var("STRATA_TEST_PORT") };
        let settings =
            Settings::from_config(&config(serde_json::json!({ "key": "k" }))).expect("resolves");
        assert_eq!(settings.key, "k");
        assert_eq!(settings.port, 8123);

        let settings = Settings::from_config(&config(
            serde_json::json!({ "key": "k", "port": "9000" }),
        ))
        .expect("resolves");
        assert_eq!(settings.port, 9000);
    }

    /// An `Option` field is absent rather than an error, and a value that cannot
    /// parse names the field.
    #[test]
    fn optional_is_none_and_bad_values_error() {
        unsafe { std::env::remove_var("STRATA_TEST_REGION") };
        let settings =
            Settings::from_config(&config(serde_json::json!({ "key": "k" }))).expect("resolves");
        assert_eq!(settings.region, None);

        let error = Settings::from_config(&config(
            serde_json::json!({ "key": "k", "port": "not-a-port" }),
        ))
        .expect_err("unparsable port");
        assert!(error.to_string().contains("`port`"), "{error}");
    }

    /// What a host reads to report a provider's settings before mounting.
    #[test]
    fn the_schema_describes_each_setting() {
        let schema = Settings::config_schema();
        let key = &schema.fields[0];
        assert_eq!(key.name, "key");
        assert!(!key.nullable);
        assert_eq!(key.description.as_deref(), Some("the key"));
        let annotations = key.annotations.to_map();
        assert_eq!(
            annotations.get("env").map(String::as_str),
            Some("STRATA_TEST_UNSET")
        );
        assert_eq!(annotations.get("secret").map(String::as_str), Some("true"));

        // A default makes a field satisfiable, so it is not required.
        assert!(schema.fields[1].nullable);
        assert!(schema.fields[2].nullable);
    }
}

