name: Tests

on:
  push:
    branches: [main]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    name: Lint checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - uses: taiki-e/install-action@just
      - uses: taiki-e/install-action@protoc

      - name: Run lint checks
        run: just lint
        env:
          RUSTFLAGS: -D warnings

  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@protoc

      - name: Run tests
        run: cargo test --workspace
        env:
          HTTP_CLIENT_CACHE: "1"
